### ISSUE TITLE
I need help on multiple things markbot says is missing

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/plan-a-website#1]
@hellachella @raven-rhea

so there are things wrong with my file I guess?

![Screen Shot 2021-03-05 at 8 10 48 AM](https://user-images.githubusercontent.com/77282460/110120062-8d07f580-7d8a-11eb-9e0a-cb2f481e5e3a.png)
This sreenshot says No mark bot file was found I did fork it im sure of it what do I do? Do i have to start over?

![Screen Shot 2021-03-05 at 8 11 32 AM](https://user-images.githubusercontent.com/77282460/110120343-ed973280-7d8a-11eb-9b38-1378ac8cc702.png)
This sreenshot says i'm missing files?

**Comment by raven-rhea** [comment]
This looks like the plan your website folder and think that might be why your having issues. Plan-a-website is not for markbot its just the sitemap we did in class. Make sure you fork and clone the "Code-a-website", it's the next assignment. Thats the one you need to code in and hand in. Don't worry you don't have to start over just make new .HTML files in the code-a-website folder and copy and paste the code you've done. Let me know how it goes

**Comment by EmmaJLussier** [comment]
Thanks Raven! Do you know if I happen miss the due date on this assignment could I catch up in lab?

**Comment by raven-rhea** [comment]
The code-a-website is due at the beginning of class, so you got the weekend still. I think Plan-a-website was at the end of last class
